# Generated by Django 2.2.1 on 2019-05-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('D', 'Director'), ('S', 'Senior'), ('R', 'Researcher')], default='R', max_length=20),
        ),
    ]
