# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-05 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190508_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='attach',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b'uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
